### PR TITLE
0.2 cleanup

### PR DESCRIPTION
**Pull request by xlz**
@SteveSmithStyku I added some environment variables to control transfer pool sizes

```
LIBFREENECT2_RGB_TRANSFER_SIZE (default 0x4000)
LIBFREENECT2_RGB_TRANSFERS (default 20)
LIBFREENECT2_IR_PACKETS (default 8)
LIBFREENECT2_IR_TRANSFERS (default 60)
```

@wiedemeyer 
The new internal API policy:

Packet processors should report internal errors by setting
good() to false, and pass the last frame to the user with
status set to 1.

Currently CUDA, OpenCL, Tegra, and VAAPI have been added
with the error propagation. CPU, OpenGL, and VT have no
error checking in place so they do not report errors.
TurboJPEG seems to produce non-fatal errors so it also
does not propagate errors.

The user should check the received frame's status
for errors. If there are errors, the user should stop the
device and exit.

When good() is false, the processor->process()
will no longer be called, and if the user continues to
call waitForNewFrame(), it will hang.

### CODE REVIEW

**Comment by wiedemeyer** [comment]
Hi @xlz
the changes are looking fine. I checked out the PR locally and updated the kinect2_bridge accordingly.
The changes are in a branch (https://github.com/code-iai/iai_kinect2/tree/libfreenect2_v0.2_api) because I use `#if LIBFREENECT2_API_VERSION >= 2` to make the code backward compatible and it will not work with the current master until the changes are merged.
Thanks for letting me know.

**Comment by xlz** [comment]
Oh, this PR was supposed to go to the upstream. I was wondering why it didn't show up.

**Comment by xlz** [comment]
@wiedemeyer I checked your changes wrt to this "API changes" here.

I mean you should check nonzero `->status` as errors, not `1` as errors. It's possible some other values may be used to represent some other rrors in the future.

Also, you don't need to check `->format` for errors. It's only informative, and right now the only meaningful use is to distinguish RGBX and BGRX.

Also, do you really need `cv::cvtColor(tmp, images[COLOR_HD], CV_BGRA2BGR);`? I suppose BGRA is faster for computatoin than BGR.

I'll

**Comment by wiedemeyer** [comment]
Ok, I changed the status check to `!= 0`. The format check is not for checking errors, it just ensures that the format is as expected.
I guess most nodes expect BGR, so I think it is better to not change it. Also the size of the messages would increase by 25%.

**Pull request closed without merging**
